In [1]:
import tensorflow as tf

In [7]:
#bce - binary cross-entropy

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, activation = 'linear')
])
model.compile(loss = 'mse')

In [2]:
import seaborn

In [3]:
iris = seaborn.load_dataset('iris')

In [9]:
model.fit(x = iris.petal_length, y = iris.sepal_length)

5/5 [==============================] - 0s 644us/step - loss: 74.6767


In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
from sklearn.model_selection import cross_val_score

In [21]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [26]:
cross_val_score(LinearRegression(), 
                X = iris.loc[:, ['petal_length', 'sepal_width']], 
                y = iris.sepal_length, n_jobs = 10, cv = 4, scoring = 'neg_mean_squared_error').mean()

-0.12412855384280408

In [23]:
from sklearn.metrics import SCORERS

In [24]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [27]:
import numpy as np

In [32]:
X = iris.iloc[:, 1:3].values

In [33]:
X

array([[3.5, 1.4],
       [3. , 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7],
       [3.4, 1.4],
       [3.4, 1.5],
       [2.9, 1.4],
       [3.1, 1.5],
       [3.7, 1.5],
       [3.4, 1.6],
       [3. , 1.4],
       [3. , 1.1],
       [4. , 1.2],
       [4.4, 1.5],
       [3.9, 1.3],
       [3.5, 1.4],
       [3.8, 1.7],
       [3.8, 1.5],
       [3.4, 1.7],
       [3.7, 1.5],
       [3.6, 1. ],
       [3.3, 1.7],
       [3.4, 1.9],
       [3. , 1.6],
       [3.4, 1.6],
       [3.5, 1.5],
       [3.4, 1.4],
       [3.2, 1.6],
       [3.1, 1.6],
       [3.4, 1.5],
       [4.1, 1.5],
       [4.2, 1.4],
       [3.1, 1.5],
       [3.2, 1.2],
       [3.5, 1.3],
       [3.6, 1.4],
       [3. , 1.3],
       [3.4, 1.5],
       [3.5, 1.3],
       [2.3, 1.3],
       [3.2, 1.3],
       [3.5, 1.6],
       [3.8, 1.9],
       [3. , 1.4],
       [3.8, 1.6],
       [3.2, 1.4],
       [3.7, 1.5],
       [3.3, 1.4],
       [3.2, 4.7],
       [3.2, 4.5],
       [3.1,

In [34]:
y = iris.sepal_length.values

array([1.20291972, 0.56905789])

In [44]:
np.linalg.inv(X.T.dot(X))

array([[ 0.00289857, -0.00187907],
       [-0.00187907,  0.00160534]])

In [76]:
def VectorLR(X:np.array,y:np.array):
    covarianceMatrix = np.linalg.inv(np.matmul(X.T, X))
    w = np.matmul(covarianceMatrix, np.matmul(X.T, y))
    return w

In [77]:
VectorLR(X, y)

array([1.20291972, 0.56905789])

In [83]:
X.shape

(150, 2)

In [84]:
from sklearn.linear_model import SGDRegressor

In [128]:
np.ceil(10**6 / len(y))

49.0

In [312]:
from sklearn.datasets import fetch_california_housing

In [317]:
from sklearn.preprocessing import StandardScaler

In [324]:
dataset = fetch_california_housing()

In [325]:
X, y = dataset['data'], dataset['target']

In [326]:
scaler = StandardScaler()
X = scaler.fit_transform(X)


In [335]:
%%time
lr = LinearRegression(fit_intercept=False)
lr.fit(X,y)
lr.coef_

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.68 ms


array([ 0.8296193 ,  0.11875165, -0.26552688,  0.30569623, -0.004503  ,
       -0.03932627, -0.89988565, -0.870541  ])

In [336]:
%%time
sgd = SGDRegressor(penalty = 'none', fit_intercept = False, n_iter_no_change=100)
sgd.fit(X, y)
sgd.coef_

CPU times: user 234 ms, sys: 0 ns, total: 234 ms
Wall time: 238 ms


array([ 0.83125061,  0.11460125, -0.30442547,  0.25334886, -0.00308474,
        0.01058203, -0.88384243, -0.88104032])

In [337]:
cross_val_score(lr, X, y, n_jobs=12, scoring='neg_mean_squared_error')

array([-4.69951068, -7.92237395, -6.31482471, -5.05986085, -8.00691479])

In [338]:
cross_val_score(sgd, X, y, n_jobs=12, scoring = 'neg_mean_squared_error')

array([-4.66788022, -7.8859352 , -6.20085191, -5.12375646, -7.74162186])

In [104]:
?SGDRegressor

Init signature:
SGDRegressor(
    loss='squared_loss',
    *,
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    random_state=None,
    learning_rate='invscaling',
    eta0=0.01,
    power_t=0.25,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    warm_start=False,
    average=False,
)
Docstring:     
Linear model fitted by minimizing a regularized empirical loss with SGD

SGD stands for Stochastic Gradient Descent: the gradient of the loss is
estimated each sample at a time and the model is updated along the way with
a decreasing strength schedule (aka learning rate).

The regularizer is a penalty added to the loss function that shrinks model
parameters towards the zero vector using either the squared euclidean norm
L2 or the absolute norm L1 or a combination of both (Elastic Net). If the
parameter update crosses the 0.0 value because of t